### PR TITLE
[zypp] Move dist-upgrade cache to /home/ (Fixes JB#29268)

### PR DESCRIPTION
**Pull request by thp**
This helps in situations where the rootfs is low on space.

WIP. This still needs testing.

### CODE REVIEW

**Comment by saukko** [comment]
We should maybe rm -rf the old directory in some %post or so to make sure it doesn't consume extra space.

**Comment by pycage** [comment]
Verified to work as expected. I agree that some %post scriptlet should make sure that the old dir /var/cache/pk-zypp-dist-upgrade does not consume extra space (it still holds the cache). However I have a bad feeding that such a %post scriptlet during the OS update would ruin the ongoing OS update by deleting all RPMs waiting to be installed. So maybe a %post scriptlet might not be the way to do it.

**Comment by thp** [comment]
Maybe a oneshot script that gets run once after reboot? Would we know by then if the update was successful or if we should keep the files to retry?

**Comment by thp** [comment]
@pycage will do the oneshot script changes, waiting for that here.

**Comment by pycage** [comment]
The oneshot script PR to this PR is here: https://github.com/thp/PackageKit/pull/2

**Pull request merged**
